# Generated by Django 4.2.1 on 2024-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projetmodel_logourl_alter_projetmodel_photourl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetmodel',
            name='author',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projetmodel',
            name='link',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projetmodel',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
