# Generated by Django 4.2.1 on 2024-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodels',
            name='author',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='coursemodels',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodels',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='coursemodels',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
